/**
 * Build docs/qa/defects-index.json from the Jira open-defects export so the Quality
 * Coverage Engine can use it as the Defects layer (Bugs column + "absence of defects"
 * component, weight 10%). Severity is derived from Jira Priority.
 *
 * Data below is the parsed Jira export (project -> domain, priority, summary).
 * Domain codes: I=Integrations T=TMS D=DOCK A=AI B=Back-Office
 * Priority codes: 5=Highest 4=High 3=Medium 2=Low 1=Lowest
 *
 * Usage: node scripts/index-defects.mjs
 */
import fs from 'node:fs';
import path from 'node:path';

const DOMAIN = { I: 'Integrations', T: 'TMS', D: 'DOCK', A: 'AI', B: 'Back-Office' };
const WEIGHT = { 5: 40, 4: 30, 3: 20, 2: 10, 1: 8 };

// [domainCode, priorityCode, summary]
const DEFECTS = [
  ['I',4,'KN AirportOfDeparture must be type of object STY validation error'],
  ['I',1,'KN No shipment found for given parameters in cron tracking statuses'],
  ['I',4,'KN No such file or directory in cron tracking statuses'],
  ['T',3,'Public API docs PATCH QR incorrect format for date and time'],
  ['D',3,'Slot View Share Request metadata PML users shown under incorrect account'],
  ['T',1,'audit D4 P44 Shippeo duplication of tracking points no source priority'],
  ['T',1,'audit D3 Container Tracking without SCAC Kpler tracking silently not created'],
  ['B',1,'audit D2 Back-Office MRR_YEAR hardcoded analytics will break'],
  ['T',1,'audit D1 MC cancelling one container cancels entire reservation REQ-MC-008'],
  ['T',1,'Carrier Confirmed list time displayed instead of year for past bookings'],
  ['I',5,'DHL FCA shipment was not imported'],
  ['D',1,'Public API POST dock-orders order_id not validated unique in PML scope'],
  ['T',1,'QR impossible to confirm a booking due to locked dates'],
  ['D',1,'Recurring Slots cant replan if account has imperial measurement system'],
  ['D',1,'Fix cells with statuses and actions'],
  ['T',1,'Followers deactivated by default after deleting PML user'],
  ['T',3,'Buy Sell Check rates doesnt work if no customer in TR'],
  ['T',1,'Public API POST STY9999 tracking point duplicate created'],
  ['T',1,'Issue with LBS to KG conversion while editing SR weight'],
  ['D',3,'Dock Order listing misaligned when window resized'],
  ['D',3,'Orders CSV uploads stuck in new when CSV header validation fails encoding'],
  ['D',3,'Slotify Danish phone number not validated correctly'],
  ['T',1,'QR Duration negative time when end time earlier than start time'],
  ['T',2,'Templates SAVE button doesnt become disabled after first click'],
  ['T',2,'QR level date validation issue on short range delivery pickup'],
  ['A',5,'Fix carrier invoice bugs after test env review'],
  ['I',1,'Fedex errors in cron fedex api csv tracking'],
  ['I',1,'Calvacom errors in cron calvacom tracking statuses'],
  ['I',1,'UPS missing msg field in cron ups tracking'],
  ['I',1,'MyDHL errors in cron mydhl dau'],
  ['I',1,'Dimotrans task createDimotransShipment failed'],
  ['I',1,'Teliae cron teliaeTrackingStatuses failed transform input point to STY'],
  ['I',1,'Dimotrans cron dimotransTrackingStatuses failed fetch'],
  ['D',3,'Planning missing slots in ongoing statuses real_date'],
  ['T',1,'Wrong summary of volume on CW display packing list'],
  ['T',1,'Deleted service remains in rate sheet error blocking CSW'],
  ['I',1,'Kuehne Nagel empty fields sent for tracking points planned_date'],
  ['T',1,'Tracking list NaNmin displayed if no planned date'],
  ['T',1,'Variety of issues caused by shipment-request metadata API ready to book'],
  ['T',1,'Sidebar some booking modes not translated into non English languages'],
  ['D',3,'Chat logs empty message after cancelling metadata request'],
  ['T',3,'Impossible to unselect a carrier at CSW2 level'],
  ['D',1,'My Site list empty when Show External Shipments in Tracking toggle disabled'],
  ['I',5,'DHL GF AfterCommit is not emitted kafka'],
  ['T',1,'CSW no validation error when max date time earlier than departure same day'],
  ['T',3,'Email notifications date time locations not displayed'],
  ['T',2,'BO impossible to replace carrier due to missing modes'],
  ['I',1,'Calvacom make filenames unique'],
  ['D',1,'Auto confirm failing when selecting a recurring slot at tms level'],
  ['I',1,'DHL fixes invalid metadata mapping masterbill'],
  ['D',3,'Grouping default 12:00 used when selecting date without time milkrun'],
  ['T',1,'CSW broken Assigned to Master flow'],
  ['D',3,'Dashboard carrier name not populated while exporting slots'],
  ['T',5,'Sidebar id change resulted to missing Ops navigation at carrier side'],
  ['D',1,'Visits list remove delimiters of purposes filter from filtering request'],
  ['D',3,'Slot CSV order created has pending status instead of assigned'],
  ['D',2,'Slotify company and phone number not translated other languages'],
  ['D',1,'Slotify missing attachment labels during booking'],
  ['D',3,'Slotify cannot download attachments uploaded during booking'],
  ['I',1,'Aftership updates the same tracking point webhook'],
  ['D',1,'Impossible to create a slot with dock orders upload date hour'],
  ['D',3,'Disabled metadata cant be removed in dock settings zone'],
  ['T',3,'Customers Workflow impossible to delete foreign key'],
  ['I',1,'MyDHL attachments upload errors'],
  ['T',1,'Google address house number issue address book'],
  ['D',2,'Slot view unable to add an order to a slot Assigned to Master'],
  ['D',1,'Slot capacity duration calculated incorrectly shipper based productivity'],
  ['I',2,'DHL GFW Admin BO find and remove unnecessary validations'],
  ['T',1,'Rate Sheets impossible to delete RS with carrier service foreign key'],
  ['T',1,'Tags shipper pre-shipment level tags visible on carrier side'],
  ['T',1,'QR metadata notify all carriers visible only to requesting carrier'],
  ['D',3,'On going status can be set after closed status from slot view'],
  ['D',4,'Slotify Next and Back buttons reset modal window state orders'],
  ['D',3,'Slot Replan PML settings not respected in Sea shipments with incoterms FOB'],
  ['D',3,'Slot Confirmation incidents dropdown shows all options instead of selected'],
  ['I',2,'Brinks stuck integrationBrinksQueue tasks'],
  ['T',2,'Per page value resets when page is reloaded locations'],
  ['D',3,'Slotify possible to cancel already confirmed slot'],
  ['T',1,'Invoicing export and export details are swapped'],
  ['D',1,'Dock settings cut-off time not ignored by dock users replan'],
  ['T',1,'Power Data request not sent when SR created without content'],
  ['T',1,'TMS Dash CO2 missing quantity multiplier calculating SH totals weight'],
  ['D',3,'Dock Load calendar settings ignored when building the grid hours'],
  ['T',1,'Customs invoices invoice remains assigned after deleting draft RTB'],
  ['T',1,'MC unable to add new containers to booking modal empty'],
  ['T',3,'Incorrect redirection after SSO login failed'],
  ['T',3,'Expected documents at QR level not following new add carrier'],
  ['D',3,'Dock settings cant add new customers to external partner if user blocked'],
  ['T',1,'Impossible to save No notified users selection for carrier in template'],
  ['D',3,'Slot booking carrier not recognized while booking without carrier notification'],
  ['T',1,'Deselecting a carrier group leaves incorrect active carriers'],
  ['D',3,'Export slots changed UTC location not applied to selected time range'],
  ['T',3,'Document preview not displayed for files with uppercase extension PDF'],
  ['D',3,'Dock statuses Left Site cannot be set to visits when belongs to closed group'],
  ['I',2,'Brinks stuck jobs tracking processBrinksTracking'],
  ['D',3,'SNCF screen special characters not supported'],
  ['T',1,'Public API galaxy carrier PATCH price doesnt work'],
  ['T',3,'Orders listing incorrect total weight'],
  ['D',1,'SH View cant notify PML users on tracking point update'],
  ['D',1,'Webhooks error when building webhook data for deleted slots recurring'],
  ['D',1,'SR View date picker doesnt respect contents manual totals'],
  ['T',1,'PML followers not displayed after updating SH location to PML'],
  ['T',3,'Logistic means weight isnt updated when updating cargo'],
  ['I',3,'Integrations user receives generic error instead of integration error message'],
  ['T',1,'Password-protected PDF file doesnt display in documents modal'],
  ['I',3,'UPS authorization may not work re-login rotten token'],
  ['D',3,'Milkrun impossible to cancel SH with PML due to deactivated cancelled status'],
  ['T',3,'Power data metadata not displayed for confirmed quote requests'],
  ['D',3,'Slot booking 2 logos when trying to notify the carrier galaxy'],
  ['I',3,'Elastic search SAP SRs are not indexed'],
  ['T',3,'Contact info not displayed for spectator account followers'],
  ['D',3,'Recurring slots cant assign two milkruns to the same slot'],
  ['T',3,'Impossible to delete an order via public API specific case foreign key'],
  ['D',3,'Recurring slots No Partner in the name even if partner added'],
  ['T',4,'CSW packing list cleared after opening a new app tab'],
  ['D',3,'Dont show slot email phone number if not available broken UI'],
  ['I',3,'Fedex selection lbs in custom invoice throws error when confirming shipment'],
  ['D',3,'Problems with unbroken shipment slot link address'],
  ['T',3,'Incorrect time format local instead of UTC saved during tracking point confirmation'],
  ['T',3,'Smart lists data from xlsx doesnt correspond to displayed list delayed shipments'],
  ['T',3,'QR email notification not sent after updating packing list'],
  ['D',3,'Load Week time per slot added even if manual duration defined'],
  ['T',2,'Token template incorrect encoding of ampersand Duties Taxes'],
  ['T',2,'Milkrun brothers modal missing hours inside the modal'],
  ['D',4,'Emails error on sending confirmation email btn not defined'],
  ['D',4,'Emailing carrier doesnt receive slot-booking-canceled email'],
  ['T',3,'Multi-account impossible to switch back to the main account'],
  ['D',3,'When confirming TP in SH email about rescheduling the slot is sent'],
  ['T',2,'Customs invoices line unit cost validation mismatch with DB decimals'],
  ['D',3,'Slot booking missing translation of delivered in orders date title'],
  ['D',3,'Dock order setting accept orders outside of date range does not work'],
  ['D',3,'PML user cannot replan shipment to another recurring slot grouping'],
  ['T',4,'Rate Sheets price doesnt recalculate if carrier was selected CSW'],
  ['D',3,'Slotify last available slot at end of zone window calculated incorrectly'],
  ['I',3,'Teliae cron crash on check tracking points fast-csv'],
  ['D',3,'Emailing replace email template for PMLs sent on SH cancellation'],
  ['D',3,'Grouping incorrect booker data when booking a new slot'],
  ['T',3,'Modal accepting terms doesnt appear for languages other than EN FR'],
  ['D',3,'Week picker simple calendar loaded when replanning slot on slow connection'],
  ['T',3,'Spectator doesnt have access to attachment from CSW'],
  ['D',3,'SMS not sent if sender account name has special characters'],
  ['D',3,'Visit empty patch request body fails with error'],
  ['T',3,'BO page crash when opening general user settings if phone number null'],
  ['T',3,'TG generated attachment could not be updated documents'],
  ['T',3,'Emails error when replanning tracking point missing in dictionary'],
  ['D',3,'Auto slotbook no check of slot booker type carrier or shipper'],
  ['T',2,'Templates auto-highlighted carrier not actually selected direct booking'],
  ['T',3,'TG error when sending GET request with invalid parameter attachments'],
  ['T',3,'Invites email not sent to new carrier user if existing user invited same time'],
  ['T',1,'Logo not properly displayed in NEW CARRIER buyer'],
  ['T',1,'BO carriers some UNLOCODE doesnt appear properly in country column'],
  ['T',1,'BO carrier visibility users FLAG display issue'],
  ['T',4,'Incorrect order of tracking points TP same date'],
  ['D',3,'SH View when booking a slot possible to select arrival earlier than departure'],
  ['T',3,'BO shippers page crashes when clicking outside the modal technical tab'],
  ['T',3,'API de-assigning order lines from unconfirmed SR not allowed'],
  ['D',3,'Cant replan book a slot on SH view to a recurring slot'],
  ['T',3,'DGD non mandatory fields require to be filled confirm disabled'],
  ['D',3,'Slot View page incorrect slot windows shown when bad internet connection'],
  ['T',3,'Country not saved correctly after creating a location for USA'],
  ['I',3,'DHL GF error response from API Booking ID Not Found'],
  ['D',3,'SH View updating tracking point modal ignores contents totals linear meters'],
  ['D',3,'Slot View page replan slot modal ignores cargo totals'],
  ['D',3,'Grouping assign shipments to the group modal ignores contents totals'],
  ['D',3,'Grouping grouped pick up and delivery modal ignores contents totals'],
  ['D',3,'Grouping group pickup modal ignores contents totals'],
  ['D',3,'SR SH view update pickup delivery location modal ignores contents totals'],
  ['D',3,'QR view page confirmation date picker ignores contents totals'],
  ['D',3,'SR view page confirmation date picker ignores contents totals'],
  ['D',3,'SR QR listings multi-confirm modal ignores contents totals'],
  ['T',3,'TR modal for TR group creation doesnt open'],
  ['I',4,'Brinks invalid hawb number'],
  ['T',3,'Milkrun impossible to delete last leg'],
  ['T',3,'Templates total linear meters not saved'],
  ['D',3,'CSW incorrect zones available if PML has 1 customer'],
  ['D',3,'Slot View after updating metadata value not refreshed in modal'],
  ['T',3,'Shipper carrier connection remains in DB when carrier deactivated in BO'],
  ['I',1,'UPS cancel shipment bug on PROD invoice date'],
  ['T',3,'SR uploading more than 5 files generates memory leak metadata'],
  ['T',3,'Add new leg modal confirm button doesnt become disabled milkrun'],
  ['T',3,'Tooltips in new sidebar not stylized properly'],
  ['T',5,'Public API some endpoints return 502 even when processed correctly dock-orders'],
  ['T',3,'Impossible to export transport requests by user with limited access'],
  ['T',3,'Address book incorrect location counter value pagination broken'],
  ['D',3,'QR slot booked without time when confirming QR on carrier side'],
  ['D',2,'QR after updating delivery location shipper cant save auto-confirmed quote'],
  ['I',3,'Peripass slot replan does not trigger integration visit'],
  ['I',3,'Shippeo webhooks authorization not work for shipper 7377 unauthorized'],
  ['T',3,'Attachments not saved in RTB'],
  ['T',3,'Black tooltip doesnt show full carriers rates on orders page'],
  ['T',3,'Dashboard advanced filter breaks displaying of graphs last year'],
  ['D',4,'Slot CSV update and merge contents'],
  ['T',3,'Impossible to create update custom invoice with zero unit net gross weight'],
  ['T',2,'Emailing error on sending attachment-special-label email'],
  ['D',2,'Slot booking skipping customer selection step opens empty modal'],
  ['T',3,'Impossible to cancel SR created from orders after deleting a leg'],
  ['T',1,'Public API PUT galaxy shipments contents doesnt work with dangerous goods'],
  ['T',3,'Orders modal for service with mandatory incoterms is broken'],
  ['T',3,'Duplicated internal ref due to slowness and lack of validation'],
  ['T',3,'User without api role doesnt have access to many pages'],
  ['T',3,'Deleting file from SR not actually deleted'],
  ['T',2,'API POST upload doc error caused by library detecting file type'],
  ['I',1,'Attachments scan expired presigned URLs cause kue jobs to stuck'],
  ['T',3,'Public API replace contents of SH product type instead of content type chat'],
  ['T',2,'Chat incorrect translation when requesting metadata'],
  ['T',2,'BO impossible to deactivate the SD filter on all shippers page'],
  ['T',1,'Public tracking page content jumping on opening modal errors console'],
  ['T',3,'Bell notifications unavailable due to websocket request to localhost'],
  ['T',3,'Public API when creating tracking point comment not sent sea'],
  ['T',3,'Dashboards invoicing difference in values on expenses tab carrier'],
  ['T',3,'Incorrect translations of goods types for cargo'],
  ['T',3,'Booker cannot upload document type metadata if not activated in account'],
  ['I',3,'Shippeo unauthorized errors'],
  ['T',3,'QR all carriers see message about adding tracking number by selected carrier'],
  ['T',3,'Public API GET invoicing by SR returns not priced for SR with prices'],
  ['T',3,'Transport plan API status quoted instead of on quote'],
  ['T',3,'BO users state not saved when switching between tabs'],
  ['T',3,'Impossible to open a booking with prices in non-default currency'],
  ['T',3,'QR time range displayed when changing the quote time by carrier'],
  ['T',3,'Impossible to request info for tracking point created by incoterms sea mode'],
  ['D',3,'Check capacity when confirming replan or slot booking race condition'],
  ['T',2,'Public page issue with driver role tracking'],
  ['T',3,'Shared component issue with visible tooltip indicator'],
  ['T',3,'API SR internal_ref cant be updated'],
  ['D',3,'Incident reported for one TP is written into both PML to PML'],
  ['T',3,'Booking listing location filter doesnt work for shipments with updated address'],
  ['T',3,'Bookings from another account displayed after creating account existing user ACL'],
  ['T',3,'Booking repeat no validation for deleted zone'],
  ['D',2,'Broken search in external partners dock settings notify'],
  ['D',3,'Replanning slot does not replan all grouped shipments'],
  ['T',3,'No email notification after adding attachment to TR undefined scope'],
  ['T',3,'BO replace carrier feature timeout error 504'],
  ['D',2,'Customer slotify link can be edited by users without permissions'],
  ['T',3,'Self-admin carrier users mode filter doesnt work correctly'],
  ['T',2,'Translation issue with diacritics French Spanish'],
  ['D',3,'Corrupted files and files with empty names cause errors when attached slotify'],
  ['T',3,'Public API update location by SR id error'],
  ['T',3,'Container transit not applied to all shipments when selecting all containers'],
  ['T',2,'Imperial system incorrect measurement system in multivision listing'],
  ['T',2,'Imperial system incorrect measurement system in orders-updates listing'],
  ['T',3,'Imperial system email notifications not in recipient default measurement system'],
  ['T',1,'Impossible to confirm a booking by carrier'],
  ['D',3,'Webhooks wrong scope in notification emails visit'],
  ['T',3,'Invites invalid token when invited a colleague'],
  ['T',3,'TG error trackings are not found public tracking page'],
  ['T',2,'Impossible to send a quote'],
  ['T',3,'Admin app customer-auth credentials auth data lost when editing'],
  ['D',3,'Remove slots_orders creation for API endpoints duplicated orders'],
  ['I',3,'Peripass slot duration calculated incorrectly'],
  ['D',3,'Custom settings not respected in freeze features planning replan cancel'],
];

const STOP = new Set('audit error errors issue impossible incorrect when from with that this does doesnt cant not the and for api page user when after before slot slots into level value cron task failed bug fix bugs button modal view list listing data field type code show used'.split(' '));
function toks(s) {
  return [...new Set((String(s).toLowerCase().match(/[a-zа-я0-9]{4,}/gi) || []).filter((w) => !STOP.has(w)))];
}

const byDomain = {};
const items = DEFECTS.map(([dc, pc, s]) => {
  const domain = DOMAIN[dc];
  const w = WEIGHT[pc];
  (byDomain[domain] = byDomain[domain] || { open: 0, weight: 0, high: 0 });
  byDomain[domain].open++;
  byDomain[domain].weight += w;
  if (pc >= 4) byDomain[domain].high++;
  return { d: domain, w, tk: toks(s) };
});

const OUT = path.resolve(process.cwd(), 'docs/qa/defects-index.json');
const index = { source: 'Jira open defects export 2026-06-16', total: items.length, byDomain, items };
fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, JSON.stringify(index));
console.log(`defects indexed: ${items.length}`);
console.log('byDomain:', JSON.stringify(byDomain));
