export const TaskStatus = {
  PENDING: 'PENDING',
  RUNNING: 'RUNNING',
  DONE: 'DONE',
  FAILED: 'FAILED',
} as const;

export const RunStatus = {
  PENDING: 'PENDING',
  RUNNING: 'RUNNING',
  DONE: 'DONE',
  FAILED: 'FAILED',
} as const;

export const StageStatus = {
  PENDING: 'PENDING',
  RUNNING: 'RUNNING',
  DONE: 'DONE',
  FAILED: 'FAILED',
  SKIPPED: 'SKIPPED',
} as const;

export const WfTaskStatus = {
  NEW: 'NEW',
  ANALYZING: 'ANALYZING',
  NEEDS_CLARIFICATION: 'NEEDS_CLARIFICATION',
  WAITING_FOR_HUMAN: 'WAITING_FOR_HUMAN',
  CLARIFICATION_RECEIVED: 'CLARIFICATION_RECEIVED',
  READY_FOR_EXECUTION: 'READY_FOR_EXECUTION',
  IN_PROGRESS: 'IN_PROGRESS',
  COMMITTED: 'COMMITTED',
  READY_FOR_REVIEW: 'READY_FOR_REVIEW',
  BLOCKED: 'BLOCKED',
  ESCALATED: 'ESCALATED',
  DONE: 'DONE',
  CANCELLED: 'CANCELLED',
} as const;

export const WfEventType = {
  TASK_CREATED: 'TASK_CREATED',
  ANALYSIS_STARTED: 'ANALYSIS_STARTED',
  ANALYSIS_COMPLETED: 'ANALYSIS_COMPLETED',
  QUESTION_CREATED: 'QUESTION_CREATED',
  QUESTION_SENT: 'QUESTION_SENT',
  ANSWER_RECEIVED: 'ANSWER_RECEIVED',
  STATUS_CHANGED: 'STATUS_CHANGED',
  PING_SENT: 'PING_SENT',
  ESCALATION_SENT: 'ESCALATION_SENT',
  EXECUTION_STARTED: 'EXECUTION_STARTED',
  COMMIT_CREATED: 'COMMIT_CREATED',
  PR_CREATED: 'PR_CREATED',
  TASK_DONE: 'TASK_DONE',
  TASK_CANCELLED: 'TASK_CANCELLED',
} as const;

export const WfJobType = {
  ANALYZE_TASK: 'ANALYZE_TASK',
  REANALYZE_TASK: 'REANALYZE_TASK',
  SEND_QUESTION: 'SEND_QUESTION',
  SEND_REMINDER: 'SEND_REMINDER',
  ESCALATE_TASK: 'ESCALATE_TASK',
  EXECUTE_TASK: 'EXECUTE_TASK',
  RUN_TESTS: 'RUN_TESTS',
  COMMIT_CHANGES: 'COMMIT_CHANGES',
  CREATE_REVIEW_SUMMARY: 'CREATE_REVIEW_SUMMARY',
  SYNC_EXTERNAL_STATUS: 'SYNC_EXTERNAL_STATUS',
} as const;

export const WfJobStatus = {
  PENDING: 'PENDING',
  RUNNING: 'RUNNING',
  DONE: 'DONE',
  FAILED: 'FAILED',
} as const;

export const IntakeJobType = {
  TRANSCRIBE: 'TRANSCRIBE',
  GENERATE_QUESTIONNAIRE: 'GENERATE_QUESTIONNAIRE',
  GENERATE_REQUIREMENT_CARD: 'GENERATE_REQUIREMENT_CARD',
  CREATE_JIRA_ISSUE: 'CREATE_JIRA_ISSUE',
} as const;

export const IntakeJobStatus = {
  PENDING: 'PENDING',
  RUNNING: 'RUNNING',
  DONE: 'DONE',
  FAILED: 'FAILED',
} as const;

export type WfJobTypeValue = (typeof WfJobType)[keyof typeof WfJobType];
export type WfTaskStatusValue = (typeof WfTaskStatus)[keyof typeof WfTaskStatus];
export type IntakeJobTypeValue = (typeof IntakeJobType)[keyof typeof IntakeJobType];
